#!/usr/bin/env python3
"""Generate src/ids.h, src/ids.cpp, and src/object_catalog.cpp from the
original game's Data/values.lua tileslist. Run manually when the enum
universe needs to grow. Also emits tools/sprite_manifest.txt listing the
sprite filenames the engine expects, which copy_sprites.py consumes.

Invocation:
  python tools/gen_ids.py --values original-baba-is-you/Data/values.lua
"""
import argparse
import re
import sys
from pathlib import Path

# Reuse the palette PNG reader from import_baba_level.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from import_baba_level import read_palette_pixel  # noqa: E402


def parse_tileslist(values_lua):
    text = Path(values_lua).read_text(encoding='utf-8', errors='replace')
    start = text.find('tileslist =')
    pattern = re.compile(r'object(\d{3})\s*=\s*\{([^{}]*(?:\{[^{}]*\}[^{}]*)*)\}', re.S)
    records = []
    for m in pattern.finditer(text, start):
        body = m.group(2)
        rec = {}
        for key in ('name', 'sprite', 'unittype'):
            mm = re.search(rf'{key}\s*=\s*"([^"]*)"', body)
            if mm:
                rec[key] = mm.group(1)
        for key in ('type', 'tiling', 'layer'):
            mm = re.search(rf'{key}\s*=\s*(-?\d+)', body)
            if mm:
                rec[key] = int(mm.group(1))
        for key in ('tile', 'colour', 'active', 'activecolour'):
            mm = re.search(rf'{key}\s*=\s*\{{\s*(-?\d+)\s*,\s*(-?\d+)\s*\}}', body)
            if mm:
                rec[key] = [int(mm.group(1)), int(mm.group(2))]
        if 'name' not in rec:
            continue
        records.append(rec)
    return records


def pascal(name):
    parts = re.split(r'[^a-zA-Z0-9]+', name)
    return ''.join(p.capitalize() for p in parts if p)


def gen(values_lua, out_dir):
    recs = parse_tileslist(values_lua)
    default_palette = Path(values_lua).parent / 'Palettes' / 'default.png'

    def tint_for(coord):
        if not coord:
            return (255, 255, 255)
        rgb = read_palette_pixel(default_palette, coord[0], coord[1])
        return rgb if rgb else (255, 255, 255)
    # Dedup objects by name (keep first)
    seen_obj = {}
    objects = []
    for r in recs:
        if r.get('unittype') == 'object' and r['name'] not in seen_obj:
            seen_obj[r['name']] = r
            objects.append(r)
    # Dedup texts by name
    seen_tx = {}
    texts = []
    for r in recs:
        if r.get('unittype') == 'text' and r['name'] and r['name'] not in seen_tx:
            seen_tx[r['name']] = r
            texts.append(r)

    # Order: keep original engine order where we can, then alphabetical.
    legacy_objects = [
        'baba', 'flag', 'wall', 'rock', 'grass', 'flower', 'tile', 'cloud',
        'star', 'brick', 'water', 'ice', 'hedge', 'fence',
    ]
    legacy_text = [
        'text_is', 'text_and', 'text_not', 'text_baba', 'text_flag',
        'text_wall', 'text_rock', 'text_you', 'text_win', 'text_stop',
        'text_push', 'text_move', 'text_defeat',
    ]
    # Sort so legacy come first (existing level JSONs keep working), rest alphabetical.
    obj_order = [name for name in legacy_objects if name in seen_obj]
    obj_order += sorted(n for n in seen_obj if n not in set(legacy_objects))
    tx_order = [name for name in legacy_text if name in seen_tx]
    tx_order += sorted(n for n in seen_tx if n not in set(legacy_text))

    ordered_objects = [seen_obj[n] for n in obj_order]
    ordered_texts = [seen_tx[n] for n in tx_order]

    # ------------------------------------------------------------------ ids.h
    ids_h = [
        '#pragma once',
        '',
        '#include <cstdint>',
        '#include <optional>',
        '#include <string_view>',
        '',
        '// Auto-generated by tools/gen_ids.py — do not edit by hand.',
        '',
        'enum class ObjectId : std::uint8_t {',
    ]
    for r in ordered_objects:
        ids_h.append(f'  {pascal(r["name"])},  // {r["name"]}')
    ids_h.append('  kCount,')
    ids_h.append('};')
    ids_h.append('')
    ids_h.append('enum class TextId : std::uint16_t {')
    for r in ordered_texts:
        short = r['name'][len('text_'):] if r['name'].startswith('text_') else r['name']
        ids_h.append(f'  {pascal(short)},  // {r["name"]} (type {r.get("type", -1)})')
    ids_h.append('  kCount,')
    ids_h.append('};')
    ids_h.append('')
    ids_h.extend([
        'enum class Direction : std::uint8_t {',
        '  Right,',
        '  Up,',
        '  Left,',
        '  Down,',
        '};',
        '',
        'enum class TextCategory : std::uint8_t {',
        '  Noun,       // type 0',
        '  Verb,       // type 1 (is/has/make/eat/fear/follow)',
        '  Property,   // type 2',
        '  Lonely,     // type 3',
        '  Modifier,   // type 4 (not)',
        '  Conjunction,// type 6 (and)',
        '  RelOp,      // type 7 (near/on/facing)',
        '};',
        '',
        'enum class Tiling : std::int8_t {',
        '  None = -1,      // single frame, no variants',
        '  AutoTile = 1,   // 16-bitmask neighbor-aware (walls, brick, grass)',
        '  Animated = 0,   // 3-frame idle, no direction (skull, ghost)',
        '  Directional = 2,// 4 facing slots x 3 frames (baba, keke, me)',
        '  Belt = 3,       // belt-specific multi-variant',
        '};',
        '',
        'inline constexpr int kObjectCount = static_cast<int>(ObjectId::kCount);',
        'inline constexpr int kTextCount = static_cast<int>(TextId::kCount);',
        '',
        'struct ObjectInfo {',
        '  std::string_view name;    // canonical id ("baba", "wall", ...)',
        '  std::string_view sprite;  // on-disk sprite basename — usually == name, but',
        '                            // some objects reuse another\'s sprite (lava→water).',
        '  int tile_x, tile_y;       // palette tile coord from values.lua',
        '  int colour_x, colour_y;   // palette colour coord',
        '  int layer;                // render layer (higher = on top)',
        '  Tiling tiling;',
        '  unsigned char tint_r, tint_g, tint_b;  // default palette rgb',
        '};',
        '',
        'struct TextInfo {',
        '  std::string_view name;    // sprite base ("text_baba", ...)',
        '  std::string_view short_name;  // without "text_" prefix',
        '  int tile_x, tile_y;',
        '  int colour_x, colour_y;',
        '  int active_x, active_y;   // tint when the text is part of an active rule',
        '  int layer;',
        '  TextCategory category;',
        '  unsigned char tint_r, tint_g, tint_b;',
        '};',
        '',
        'const ObjectInfo& InfoOf(ObjectId id);',
        'const TextInfo& InfoOf(TextId id);',
        '',
        'std::string_view NameOf(ObjectId id);',
        'std::string_view NameOf(TextId id);',
        'std::string_view NameOf(Direction dir);',
        '',
        'TextCategory CategoryOf(TextId id);',
        'int LayerOf(ObjectId id);',
        'int LayerOf(TextId id);',
        '',
        '// True if the object uses 16-variant auto-tiling.',
        'bool IsAutoTiled(ObjectId id);',
        '',
        '// True if the object uses 4 directional sprite slots.',
        'bool IsDirectional(ObjectId id);',
        '',
        'int DirectionToVariant(Direction d);',
        '',
        '// Noun text -> its corresponding object. Non-noun text returns nullopt.',
        'std::optional<ObjectId> NounToObject(TextId id);',
        '',
        '// Lookup by lowercase base name (without "text_" prefix for TextId).',
        'std::optional<ObjectId> ObjectIdFromName(std::string_view name);',
        'std::optional<TextId> TextIdFromName(std::string_view name);',
        '',
    ])

    # -------------------------------------------------------------- ids.cpp
    type_to_cat = {
        0: 'TextCategory::Noun',
        1: 'TextCategory::Verb',
        2: 'TextCategory::Property',
        3: 'TextCategory::Lonely',
        4: 'TextCategory::Modifier',
        6: 'TextCategory::Conjunction',
        7: 'TextCategory::RelOp',
    }
    # Tiling enum value -> literal
    def tiling_lit(t):
        return {
            -1: 'Tiling::None',
            0: 'Tiling::Animated',
            1: 'Tiling::AutoTile',
            2: 'Tiling::Directional',
            3: 'Tiling::Belt',
        }.get(t, 'Tiling::None')

    ids_cpp = [
        '#include "ids.h"',
        '',
        '// Auto-generated by tools/gen_ids.py — do not edit by hand.',
        '',
        'namespace {',
        '',
        'constexpr ObjectInfo kObjectInfos[kObjectCount] = {',
    ]
    for r in ordered_objects:
        tx, ty = r.get('tile', [0, 0])
        cx, cy = r.get('colour', [0, 3])
        layer = r.get('layer', 16)
        tr, tg, tb = tint_for(r.get('colour'))
        sprite = r.get('sprite', r['name'])
        ids_cpp.append(
            f'  {{"{r["name"]}", "{sprite}", {tx}, {ty}, {cx}, {cy}, {layer}, '
            f'{tiling_lit(r.get("tiling", -1))}, {tr}, {tg}, {tb}}},'
        )
    ids_cpp.append('};')
    ids_cpp.append('')
    ids_cpp.append('constexpr TextInfo kTextInfos[kTextCount] = {')
    for r in ordered_texts:
        tx, ty = r.get('tile', [0, 0])
        cx, cy = r.get('colour', [0, 3])
        ax, ay = r.get('active', r.get('activecolour', [cx, cy]))
        layer = r.get('layer', 20)
        short = r['name'][len('text_'):] if r['name'].startswith('text_') else r['name']
        cat = type_to_cat.get(r.get('type', 0), 'TextCategory::Property')
        # Text tint uses the "active" colour — that's what the original game
        # shows for text blocks participating in rules. Passive text is dimmer
        # but we don't currently track that state.
        tr, tg, tb = tint_for([ax, ay])
        ids_cpp.append(
            f'  {{"{r["name"]}", "{short}", {tx}, {ty}, {cx}, {cy}, {ax}, {ay}, '
            f'{layer}, {cat}, {tr}, {tg}, {tb}}},'
        )
    ids_cpp.append('};')
    ids_cpp.append('')
    ids_cpp.extend([
        'constexpr std::string_view kDirectionNames[4] = {',
        '    "right", "up", "left", "down",',
        '};',
        '',
        '}  // namespace',
        '',
        'const ObjectInfo& InfoOf(ObjectId id) { return kObjectInfos[static_cast<int>(id)]; }',
        'const TextInfo& InfoOf(TextId id) { return kTextInfos[static_cast<int>(id)]; }',
        '',
        'std::string_view NameOf(ObjectId id) { return kObjectInfos[static_cast<int>(id)].name; }',
        'std::string_view NameOf(TextId id) { return kTextInfos[static_cast<int>(id)].short_name; }',
        'std::string_view NameOf(Direction dir) { return kDirectionNames[static_cast<int>(dir)]; }',
        '',
        'TextCategory CategoryOf(TextId id) { return kTextInfos[static_cast<int>(id)].category; }',
        'int LayerOf(ObjectId id) { return kObjectInfos[static_cast<int>(id)].layer; }',
        'int LayerOf(TextId id) { return kTextInfos[static_cast<int>(id)].layer; }',
        '',
        'bool IsAutoTiled(ObjectId id) {',
        '  return kObjectInfos[static_cast<int>(id)].tiling == Tiling::AutoTile;',
        '}',
        'bool IsDirectional(ObjectId id) {',
        '  return kObjectInfos[static_cast<int>(id)].tiling == Tiling::Directional;',
        '}',
        '',
        'int DirectionToVariant(Direction d) {',
        '  switch (d) {',
        '    case Direction::Right: return 0;',
        '    case Direction::Up:    return 8;',
        '    case Direction::Left:  return 16;',
        '    case Direction::Down:  return 24;',
        '  }',
        '  return 0;',
        '}',
        '',
        'std::optional<ObjectId> NounToObject(TextId id) {',
        '  const auto& info = InfoOf(id);',
        '  if (info.category != TextCategory::Noun) return std::nullopt;',
        '  return ObjectIdFromName(info.short_name);',
        '}',
        '',
        'std::optional<ObjectId> ObjectIdFromName(std::string_view name) {',
        '  for (int i = 0; i < kObjectCount; ++i) {',
        '    if (kObjectInfos[i].name == name) return static_cast<ObjectId>(i);',
        '  }',
        '  return std::nullopt;',
        '}',
        '',
        'std::optional<TextId> TextIdFromName(std::string_view name) {',
        '  for (int i = 0; i < kTextCount; ++i) {',
        '    if (kTextInfos[i].short_name == name) return static_cast<TextId>(i);',
        '  }',
        '  return std::nullopt;',
        '}',
        '',
    ])

    # ------------------------------------------------- sprite manifest
    manifest = []
    seen_manifest = set()
    for r in ordered_objects:
        tiling = r.get('tiling', -1)
        # Use the sprite override (lava uses water's sprite). Multiple objects
        # can share a sprite, so dedupe to avoid wasted copy_sprites.py work.
        name = r.get('sprite', r['name'])
        variants = []
        if tiling == 1:  # auto-tile 0..15
            variants = list(range(16))
        elif tiling == 2:  # directional: 0, 8, 16, 24
            variants = [0, 8, 16, 24]
        elif tiling == 3:  # belt — 0..27 typically, keep full range to be safe
            variants = list(range(32))
        else:
            variants = [0]
        for v in variants:
            for f in (1, 2, 3):
                entry = f'{name}_{v}_{f}.png'
                if entry in seen_manifest:
                    continue
                seen_manifest.add(entry)
                manifest.append(entry)
    for r in ordered_texts:
        for f in (1, 2, 3):
            manifest.append(f'{r["name"]}_0_{f}.png')

    # ------------------------------------------------- Write outputs
    out_dir = Path(out_dir)
    (out_dir / 'src' / 'ids.h').write_text('\n'.join(ids_h), encoding='utf-8')
    (out_dir / 'src' / 'ids.cpp').write_text('\n'.join(ids_cpp), encoding='utf-8')
    manifest_path = out_dir / 'tools' / 'sprite_manifest.txt'
    manifest_path.write_text('\n'.join(manifest) + '\n', encoding='utf-8')

    print(f'objects: {len(ordered_objects)}')
    print(f'texts:   {len(ordered_texts)}')
    print(f'manifest entries: {len(manifest)}')
    print(f'wrote {out_dir}/src/ids.h, ids.cpp, tools/sprite_manifest.txt')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--values', default='original-baba-is-you/Data/values.lua')
    ap.add_argument('--out-dir', default='.')
    args = ap.parse_args()
    gen(args.values, args.out_dir)


if __name__ == '__main__':
    main()
