#include "ids.h"

// Auto-generated by tools/gen_ids.py — do not edit by hand.

namespace {

constexpr ObjectInfo kObjectInfos[kObjectCount] = {
  {"baba", "baba", 1, 0, 0, 3, 18, Tiling::Directional, 255, 255, 255},
  {"flag", "flag", 0, 2, 2, 4, 17, Tiling::None, 237, 226, 133},
  {"wall", "wall", 1, 1, 1, 1, 14, Tiling::AutoTile, 41, 49, 65},
  {"rock", "rock", 3, 0, 6, 2, 16, Tiling::None, 194, 158, 70},
  {"grass", "grass", 0, 6, 5, 0, 10, Tiling::AutoTile, 48, 56, 36},
  {"flower", "flower", 7, 7, 3, 3, 12, Tiling::None, 85, 122, 224},
  {"tile", "tile", 5, 0, 1, 0, 4, Tiling::None, 21, 24, 31},
  {"cloud", "cloud", 6, 1, 1, 4, 14, Tiling::AutoTile, 131, 200, 229},
  {"star", "star", 6, 3, 2, 4, 16, Tiling::None, 237, 226, 133},
  {"brick", "brick", 9, 9, 6, 3, 10, Tiling::AutoTile, 54, 46, 34},
  {"water", "water", 0, 1, 1, 3, 2, Tiling::AutoTile, 95, 157, 209},
  {"ice", "ice", 1, 2, 1, 2, 9, Tiling::AutoTile, 62, 118, 136},
  {"hedge", "hedge", 0, 9, 5, 1, 14, Tiling::AutoTile, 75, 92, 28},
  {"fence", "fence", 8, 8, 6, 1, 14, Tiling::AutoTile, 144, 103, 62},
  {"belt", "belt", 4, 7, 1, 1, 11, Tiling::Belt, 41, 49, 65},
  {"box", "box", 2, 7, 6, 2, 16, Tiling::None, 194, 158, 70},
  {"cursor", "cursor", 5, 10, 4, 2, 20, Tiling::None, 235, 145, 202},
  {"door", "door", 3, 5, 2, 2, 15, Tiling::None, 229, 83, 59},
  {"dust", "dust", 6, 5, 6, 2, 12, Tiling::None, 194, 158, 70},
  {"fruit", "fruit", 8, 4, 2, 2, 16, Tiling::None, 229, 83, 59},
  {"fungus", "fungus", 8, 2, 6, 1, 16, Tiling::None, 144, 103, 62},
  {"ghost", "ghost", 10, 10, 4, 2, 17, Tiling::Animated, 235, 145, 202},
  {"hand", "hand", 4, 4, 0, 3, 17, Tiling::Animated, 255, 255, 255},
  {"keke", "keke", 2, 0, 2, 2, 18, Tiling::Directional, 229, 83, 59},
  {"key", "key", 9, 6, 2, 4, 16, Tiling::None, 237, 226, 133},
  {"lava", "water", 11, 0, 2, 3, 2, Tiling::AutoTile, 228, 153, 80},
  {"line", "line", 8, 10, 0, 3, 20, Tiling::AutoTile, 255, 255, 255},
  {"love", "love", 2, 5, 4, 2, 16, Tiling::None, 235, 145, 202},
  {"me", "me", 10, 7, 3, 1, 18, Tiling::Directional, 142, 94, 156},
  {"moon", "moon", 6, 8, 2, 4, 16, Tiling::None, 237, 226, 133},
  {"orb", "orb", 4, 9, 4, 1, 17, Tiling::None, 217, 57, 106},
  {"pillar", "pillar", 7, 1, 0, 1, 16, Tiling::None, 115, 115, 115},
  {"rose", "rose", 3, 2, 2, 2, 16, Tiling::None, 229, 83, 59},
  {"skull", "skull", 11, 5, 2, 1, 16, Tiling::Animated, 130, 38, 28},
  {"statue", "statue", 2, 10, 0, 1, 17, Tiling::Animated, 115, 115, 115},
  {"tree", "tree", 8, 6, 5, 2, 15, Tiling::None, 92, 131, 57},
};

constexpr TextInfo kTextInfos[kTextCount] = {
  {"text_is", "is", 1, 3, 0, 1, 0, 3, 20, TextCategory::Verb, 255, 255, 255},
  {"text_and", "and", 6, 0, 0, 1, 0, 3, 20, TextCategory::Conjunction, 255, 255, 255},
  {"text_not", "not", 0, 5, 2, 1, 2, 2, 20, TextCategory::Modifier, 229, 83, 59},
  {"text_baba", "baba", 9, 1, 4, 0, 4, 1, 20, TextCategory::Noun, 217, 57, 106},
  {"text_flag", "flag", 11, 1, 6, 1, 2, 4, 20, TextCategory::Noun, 237, 226, 133},
  {"text_wall", "wall", 11, 2, 1, 1, 0, 1, 20, TextCategory::Noun, 115, 115, 115},
  {"text_rock", "rock", 9, 2, 6, 0, 6, 1, 20, TextCategory::Noun, 144, 103, 62},
  {"text_you", "you", 11, 4, 4, 0, 4, 1, 20, TextCategory::Property, 217, 57, 106},
  {"text_win", "win", 10, 3, 6, 1, 2, 4, 20, TextCategory::Property, 237, 226, 133},
  {"text_stop", "stop", 0, 4, 5, 0, 5, 1, 20, TextCategory::Property, 75, 92, 28},
  {"text_push", "push", 11, 3, 6, 0, 6, 1, 20, TextCategory::Property, 144, 103, 62},
  {"text_move", "move", 1, 4, 5, 1, 5, 3, 20, TextCategory::Property, 165, 177, 63},
  {"text_defeat", "defeat", 10, 5, 2, 0, 2, 1, 20, TextCategory::Property, 130, 38, 28},
  {"default", "default", 0, 12, 1, 1, 3, 2, 20, TextCategory::Property, 71, 89, 177},
  {"text_all", "all", 4, 2, 0, 1, 0, 3, 20, TextCategory::Noun, 255, 255, 255},
  {"text_belt", "belt", 9, 7, 1, 2, 1, 3, 20, TextCategory::Noun, 95, 157, 209},
  {"text_best", "best", 2, 4, 2, 3, 2, 4, 20, TextCategory::Property, 237, 226, 133},
  {"text_blue", "blue", 7, 6, 3, 2, 3, 3, 20, TextCategory::Property, 85, 122, 224},
  {"text_bonus", "bonus", 5, 9, 4, 0, 4, 1, 20, TextCategory::Property, 217, 57, 106},
  {"text_box", "box", 3, 7, 6, 0, 6, 1, 20, TextCategory::Noun, 144, 103, 62},
  {"text_brick", "brick", 10, 9, 6, 0, 6, 1, 20, TextCategory::Noun, 144, 103, 62},
  {"text_cloud", "cloud", 6, 2, 1, 3, 1, 4, 20, TextCategory::Noun, 131, 200, 229},
  {"text_door", "door", 3, 6, 2, 1, 2, 2, 20, TextCategory::Noun, 229, 83, 59},
  {"text_down", "down", 5, 5, 1, 3, 1, 4, 20, TextCategory::Property, 131, 200, 229},
  {"text_dust", "dust", 6, 6, 6, 2, 2, 4, 20, TextCategory::Noun, 237, 226, 133},
  {"text_eat", "eat", 0, 10, 2, 1, 2, 2, 20, TextCategory::Verb, 229, 83, 59},
  {"text_empty", "empty", 2, 1, 0, 1, 0, 3, 20, TextCategory::Noun, 255, 255, 255},
  {"text_facing", "facing", 9, 10, 0, 2, 0, 3, 20, TextCategory::RelOp, 255, 255, 255},
  {"text_fall", "fall", 6, 7, 5, 1, 5, 3, 20, TextCategory::Property, 165, 177, 63},
  {"text_fear", "fear", 7, 10, 2, 1, 2, 2, 20, TextCategory::Verb, 229, 83, 59},
  {"text_fence", "fence", 8, 7, 6, 0, 6, 1, 20, TextCategory::Noun, 144, 103, 62},
  {"text_float", "float", 9, 0, 1, 2, 1, 4, 20, TextCategory::Property, 131, 200, 229},
  {"text_flower", "flower", 7, 5, 3, 2, 3, 3, 20, TextCategory::Noun, 85, 122, 224},
  {"text_follow", "follow", 8, 0, 5, 0, 5, 2, 20, TextCategory::Verb, 92, 131, 57},
  {"text_fruit", "fruit", 8, 3, 2, 1, 2, 2, 20, TextCategory::Noun, 229, 83, 59},
  {"text_fungus", "fungus", 8, 1, 6, 0, 6, 1, 20, TextCategory::Noun, 144, 103, 62},
  {"text_ghost", "ghost", 11, 10, 4, 1, 4, 2, 20, TextCategory::Noun, 235, 145, 202},
  {"text_grass", "grass", 4, 0, 5, 1, 5, 3, 20, TextCategory::Noun, 165, 177, 63},
  {"text_group", "group", 7, 9, 3, 2, 3, 3, 20, TextCategory::Noun, 85, 122, 224},
  {"text_hand", "hand", 4, 5, 0, 1, 0, 3, 20, TextCategory::Noun, 255, 255, 255},
  {"text_has", "has", 1, 7, 0, 1, 0, 3, 20, TextCategory::Verb, 255, 255, 255},
  {"text_hedge", "hedge", 1, 9, 5, 0, 5, 1, 20, TextCategory::Noun, 75, 92, 28},
  {"text_hide", "hide", 7, 0, 3, 2, 3, 3, 20, TextCategory::Property, 85, 122, 224},
  {"text_hot", "hot", 10, 4, 2, 2, 2, 3, 20, TextCategory::Property, 228, 153, 80},
  {"text_ice", "ice", 0, 3, 1, 2, 1, 3, 20, TextCategory::Noun, 95, 157, 209},
  {"text_keke", "keke", 10, 1, 2, 1, 2, 2, 20, TextCategory::Noun, 229, 83, 59},
  {"text_key", "key", 10, 6, 6, 1, 2, 4, 20, TextCategory::Noun, 237, 226, 133},
  {"text_lava", "lava", 10, 2, 2, 2, 2, 3, 20, TextCategory::Noun, 228, 153, 80},
  {"text_left", "left", 5, 4, 1, 3, 1, 4, 20, TextCategory::Property, 131, 200, 229},
  {"text_level", "level", 2, 9, 4, 0, 4, 1, 20, TextCategory::Noun, 217, 57, 106},
  {"text_line", "line", 8, 9, 0, 2, 0, 3, 20, TextCategory::Noun, 255, 255, 255},
  {"text_lonely", "lonely", 10, 0, 2, 1, 2, 2, 20, TextCategory::Lonely, 229, 83, 59},
  {"text_love", "love", 2, 6, 4, 1, 4, 2, 20, TextCategory::Noun, 235, 145, 202},
  {"text_make", "make", 5, 7, 0, 1, 0, 3, 20, TextCategory::Verb, 255, 255, 255},
  {"text_me", "me", 11, 7, 3, 0, 3, 1, 20, TextCategory::Noun, 142, 94, 156},
  {"text_melt", "melt", 9, 4, 1, 2, 1, 3, 20, TextCategory::Property, 95, 157, 209},
  {"text_moon", "moon", 6, 9, 6, 1, 2, 4, 20, TextCategory::Noun, 237, 226, 133},
  {"text_more", "more", 3, 3, 4, 0, 4, 1, 20, TextCategory::Property, 217, 57, 106},
  {"text_near", "near", 5, 1, 0, 1, 0, 3, 20, TextCategory::RelOp, 255, 255, 255},
  {"text_on", "on", 4, 8, 0, 1, 0, 3, 20, TextCategory::RelOp, 255, 255, 255},
  {"text_open", "open", 11, 6, 6, 1, 2, 4, 20, TextCategory::Property, 237, 226, 133},
  {"text_orb", "orb", 3, 9, 4, 0, 4, 1, 20, TextCategory::Noun, 217, 57, 106},
  {"text_pillar", "pillar", 7, 2, 0, 0, 0, 1, 20, TextCategory::Noun, 115, 115, 115},
  {"text_pull", "pull", 3, 8, 6, 1, 6, 2, 20, TextCategory::Property, 194, 158, 70},
  {"text_red", "red", 7, 4, 2, 1, 2, 2, 20, TextCategory::Property, 229, 83, 59},
  {"text_right", "right", 5, 2, 1, 3, 1, 4, 20, TextCategory::Property, 131, 200, 229},
  {"text_rose", "rose", 7, 3, 2, 1, 2, 2, 20, TextCategory::Noun, 229, 83, 59},
  {"text_sad", "sad", 6, 10, 1, 1, 3, 2, 20, TextCategory::Property, 71, 89, 177},
  {"text_safe", "safe", 4, 3, 0, 1, 0, 3, 20, TextCategory::Property, 255, 255, 255},
  {"text_shift", "shift", 2, 2, 1, 2, 1, 3, 20, TextCategory::Property, 95, 157, 209},
  {"text_shut", "shut", 0, 7, 2, 1, 2, 2, 20, TextCategory::Property, 229, 83, 59},
  {"text_sink", "sink", 1, 5, 1, 2, 1, 3, 20, TextCategory::Property, 95, 157, 209},
  {"text_skull", "skull", 1, 6, 2, 0, 2, 1, 20, TextCategory::Noun, 130, 38, 28},
  {"text_sleep", "sleep", 5, 6, 1, 3, 1, 4, 20, TextCategory::Property, 131, 200, 229},
  {"text_star", "star", 6, 4, 6, 1, 2, 4, 20, TextCategory::Noun, 237, 226, 133},
  {"text_statue", "statue", 1, 10, 0, 0, 0, 1, 20, TextCategory::Noun, 115, 115, 115},
  {"text_swap", "swap", 2, 8, 3, 0, 3, 1, 20, TextCategory::Property, 142, 94, 156},
  {"text_tele", "tele", 3, 4, 1, 2, 1, 4, 20, TextCategory::Property, 131, 200, 229},
  {"text_text", "text", 4, 6, 4, 0, 4, 1, 20, TextCategory::Noun, 217, 57, 106},
  {"text_tile", "tile", 3, 1, 1, 1, 0, 1, 20, TextCategory::Noun, 115, 115, 115},
  {"text_tree", "tree", 8, 5, 5, 1, 5, 2, 20, TextCategory::Noun, 92, 131, 57},
  {"text_up", "up", 5, 3, 1, 3, 1, 4, 20, TextCategory::Property, 131, 200, 229},
  {"text_water", "water", 9, 3, 1, 2, 1, 3, 20, TextCategory::Noun, 95, 157, 209},
  {"text_weak", "weak", 4, 1, 1, 1, 1, 2, 20, TextCategory::Property, 62, 118, 136},
  {"text_wonder", "wonder", 11, 9, 0, 1, 0, 3, 20, TextCategory::Property, 255, 255, 255},
  {"text_word", "word", 0, 11, 0, 2, 0, 3, 20, TextCategory::Property, 255, 255, 255},
};

constexpr std::string_view kDirectionNames[4] = {
    "right", "up", "left", "down",
};

}  // namespace

const ObjectInfo& InfoOf(ObjectId id) { return kObjectInfos[static_cast<int>(id)]; }
const TextInfo& InfoOf(TextId id) { return kTextInfos[static_cast<int>(id)]; }

std::string_view NameOf(ObjectId id) { return kObjectInfos[static_cast<int>(id)].name; }
std::string_view NameOf(TextId id) { return kTextInfos[static_cast<int>(id)].short_name; }
std::string_view NameOf(Direction dir) { return kDirectionNames[static_cast<int>(dir)]; }

TextCategory CategoryOf(TextId id) { return kTextInfos[static_cast<int>(id)].category; }
int LayerOf(ObjectId id) { return kObjectInfos[static_cast<int>(id)].layer; }
int LayerOf(TextId id) { return kTextInfos[static_cast<int>(id)].layer; }

bool IsAutoTiled(ObjectId id) {
  return kObjectInfos[static_cast<int>(id)].tiling == Tiling::AutoTile;
}
bool IsDirectional(ObjectId id) {
  return kObjectInfos[static_cast<int>(id)].tiling == Tiling::Directional;
}

int DirectionToVariant(Direction d) {
  switch (d) {
    case Direction::Right: return 0;
    case Direction::Up:    return 8;
    case Direction::Left:  return 16;
    case Direction::Down:  return 24;
  }
  return 0;
}

std::optional<ObjectId> NounToObject(TextId id) {
  const auto& info = InfoOf(id);
  if (info.category != TextCategory::Noun) return std::nullopt;
  return ObjectIdFromName(info.short_name);
}

std::optional<ObjectId> ObjectIdFromName(std::string_view name) {
  for (int i = 0; i < kObjectCount; ++i) {
    if (kObjectInfos[i].name == name) return static_cast<ObjectId>(i);
  }
  return std::nullopt;
}

std::optional<TextId> TextIdFromName(std::string_view name) {
  for (int i = 0; i < kTextCount; ++i) {
    if (kTextInfos[i].short_name == name) return static_cast<TextId>(i);
  }
  return std::nullopt;
}
