#pragma once

#include <cstdint>
#include <optional>
#include <string_view>

// Auto-generated by tools/gen_ids.py — do not edit by hand.

enum class ObjectId : std::uint8_t {
  Baba,  // baba
  Flag,  // flag
  Wall,  // wall
  Rock,  // rock
  Grass,  // grass
  Flower,  // flower
  Tile,  // tile
  Cloud,  // cloud
  Star,  // star
  Brick,  // brick
  Water,  // water
  Ice,  // ice
  Hedge,  // hedge
  Fence,  // fence
  Belt,  // belt
  Box,  // box
  Cursor,  // cursor
  Door,  // door
  Dust,  // dust
  Fruit,  // fruit
  Fungus,  // fungus
  Ghost,  // ghost
  Hand,  // hand
  Keke,  // keke
  Key,  // key
  Lava,  // lava
  Line,  // line
  Love,  // love
  Me,  // me
  Moon,  // moon
  Orb,  // orb
  Pillar,  // pillar
  Rose,  // rose
  Skull,  // skull
  Statue,  // statue
  Tree,  // tree
  kCount,
};

enum class TextId : std::uint16_t {
  Is,  // text_is (type 1)
  And,  // text_and (type 6)
  Not,  // text_not (type 4)
  Baba,  // text_baba (type 0)
  Flag,  // text_flag (type 0)
  Wall,  // text_wall (type 0)
  Rock,  // text_rock (type 0)
  You,  // text_you (type 2)
  Win,  // text_win (type 2)
  Stop,  // text_stop (type 2)
  Push,  // text_push (type 2)
  Move,  // text_move (type 2)
  Defeat,  // text_defeat (type 2)
  Default,  // default (type 2)
  All,  // text_all (type 0)
  Belt,  // text_belt (type 0)
  Best,  // text_best (type 2)
  Blue,  // text_blue (type 2)
  Bonus,  // text_bonus (type 2)
  Box,  // text_box (type 0)
  Brick,  // text_brick (type 0)
  Cloud,  // text_cloud (type 0)
  Door,  // text_door (type 0)
  Down,  // text_down (type 2)
  Dust,  // text_dust (type 0)
  Eat,  // text_eat (type 1)
  Empty,  // text_empty (type 0)
  Facing,  // text_facing (type 7)
  Fall,  // text_fall (type 2)
  Fear,  // text_fear (type 1)
  Fence,  // text_fence (type 0)
  Float,  // text_float (type 2)
  Flower,  // text_flower (type 0)
  Follow,  // text_follow (type 1)
  Fruit,  // text_fruit (type 0)
  Fungus,  // text_fungus (type 0)
  Ghost,  // text_ghost (type 0)
  Grass,  // text_grass (type 0)
  Group,  // text_group (type 0)
  Hand,  // text_hand (type 0)
  Has,  // text_has (type 1)
  Hedge,  // text_hedge (type 0)
  Hide,  // text_hide (type 2)
  Hot,  // text_hot (type 2)
  Ice,  // text_ice (type 0)
  Keke,  // text_keke (type 0)
  Key,  // text_key (type 0)
  Lava,  // text_lava (type 0)
  Left,  // text_left (type 2)
  Level,  // text_level (type 0)
  Line,  // text_line (type 0)
  Lonely,  // text_lonely (type 3)
  Love,  // text_love (type 0)
  Make,  // text_make (type 1)
  Me,  // text_me (type 0)
  Melt,  // text_melt (type 2)
  Moon,  // text_moon (type 0)
  More,  // text_more (type 2)
  Near,  // text_near (type 7)
  On,  // text_on (type 7)
  Open,  // text_open (type 2)
  Orb,  // text_orb (type 0)
  Pillar,  // text_pillar (type 0)
  Pull,  // text_pull (type 2)
  Red,  // text_red (type 2)
  Right,  // text_right (type 2)
  Rose,  // text_rose (type 0)
  Sad,  // text_sad (type 2)
  Safe,  // text_safe (type 2)
  Shift,  // text_shift (type 2)
  Shut,  // text_shut (type 2)
  Sink,  // text_sink (type 2)
  Skull,  // text_skull (type 0)
  Sleep,  // text_sleep (type 2)
  Star,  // text_star (type 0)
  Statue,  // text_statue (type 0)
  Swap,  // text_swap (type 2)
  Tele,  // text_tele (type 2)
  Text,  // text_text (type 0)
  Tile,  // text_tile (type 0)
  Tree,  // text_tree (type 0)
  Up,  // text_up (type 2)
  Water,  // text_water (type 0)
  Weak,  // text_weak (type 2)
  Wonder,  // text_wonder (type 2)
  Word,  // text_word (type 2)
  kCount,
};

enum class Direction : std::uint8_t {
  Right,
  Up,
  Left,
  Down,
};

enum class TextCategory : std::uint8_t {
  Noun,       // type 0
  Verb,       // type 1 (is/has/make/eat/fear/follow)
  Property,   // type 2
  Lonely,     // type 3
  Modifier,   // type 4 (not)
  Conjunction,// type 6 (and)
  RelOp,      // type 7 (near/on/facing)
};

enum class Tiling : std::int8_t {
  None = -1,      // single frame, no variants
  AutoTile = 1,   // 16-bitmask neighbor-aware (walls, brick, grass)
  Animated = 0,   // 3-frame idle, no direction (skull, ghost)
  Directional = 2,// 4 facing slots x 3 frames (baba, keke, me)
  Belt = 3,       // belt-specific multi-variant
};

inline constexpr int kObjectCount = static_cast<int>(ObjectId::kCount);
inline constexpr int kTextCount = static_cast<int>(TextId::kCount);

struct ObjectInfo {
  std::string_view name;    // canonical id ("baba", "wall", ...)
  std::string_view sprite;  // on-disk sprite basename — usually == name, but
                            // some objects reuse another's sprite (lava→water).
  int tile_x, tile_y;       // palette tile coord from values.lua
  int colour_x, colour_y;   // palette colour coord
  int layer;                // render layer (higher = on top)
  Tiling tiling;
  unsigned char tint_r, tint_g, tint_b;  // default palette rgb
};

struct TextInfo {
  std::string_view name;    // sprite base ("text_baba", ...)
  std::string_view short_name;  // without "text_" prefix
  int tile_x, tile_y;
  int colour_x, colour_y;
  int active_x, active_y;   // tint when the text is part of an active rule
  int layer;
  TextCategory category;
  unsigned char tint_r, tint_g, tint_b;
};

const ObjectInfo& InfoOf(ObjectId id);
const TextInfo& InfoOf(TextId id);

std::string_view NameOf(ObjectId id);
std::string_view NameOf(TextId id);
std::string_view NameOf(Direction dir);

TextCategory CategoryOf(TextId id);
int LayerOf(ObjectId id);
int LayerOf(TextId id);

// True if the object uses 16-variant auto-tiling.
bool IsAutoTiled(ObjectId id);

// True if the object uses 4 directional sprite slots.
bool IsDirectional(ObjectId id);

int DirectionToVariant(Direction d);

// Noun text -> its corresponding object. Non-noun text returns nullopt.
std::optional<ObjectId> NounToObject(TextId id);

// Lookup by lowercase base name (without "text_" prefix for TextId).
std::optional<ObjectId> ObjectIdFromName(std::string_view name);
std::optional<TextId> TextIdFromName(std::string_view name);
